accounts/urls.py
import django.contrib.auth.views
from django.urls import path

from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('entrar/', django.contrib.auth.views.LoginView.as_view(), {
        'template_name': 'registration/login.html'
    }, name='login'),
    path('sair/', django.contrib.auth.views.LogoutView.as_view(), {
        'next_page': 'core:home'
    }, name='logout'),
    path('cadastre-se/', views.register, name='register')
]

core/urls.py
from django.urls import path

from core import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('contato/', views.contact, name='contact')
]

courses/urls.py
from django.urls import path

from courses import views

app_name = 'courses'
urlpatterns = [
    path('', views.courses, name='index'),
    path('<slug>', views.details, name='details'),
]

simplemooc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.autodiscover()

urlpatterns = [
                  path('', include('core.urls', namespace='core')),
                  path('contas/', include('accounts.urls', namespace='accounts')),
                  path('cursos/', include('courses.urls', namespace='courses')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # url das imagens

accounts/models.py
# Create your models here.

courses/models.py
from django.db import models


# Custom Manager do model Cource
class CourseManager(models.Manager):
    def search(self, query):
        # Lista os cursos que contem <query> no nome e na descrição
        return self.get_queryset().filter(
            models.Q(name__icontains=query) | models.Q(description__icontains=query)
        )


# Model Course
class Course(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descrição Simples', blank=True)
    about = models.TextField('Sobre o curso', blank=True)
    start_date = models.DateField('Data de Início', null=True, blank=True)
    image = models.ImageField(upload_to='courses/images', verbose_name='Imagem', null=True, blank=True)
    create_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    # substitui o Manager pelo Custom Manager
    objects = CourseManager()

    def __str__(self):
        return self.name

    ## Cria a url para acessar os detalhes do curso
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('courses:details', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        # ordering = ['name']   # Ascending
        ordering = ['-name']  # Descending

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(label='Nome', max_length=150)
    last_name = forms.CharField(label='Sobrenome', max_length=150)
    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Já existe um usuário com este E-mail')
        return email

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user

courses/forms.py
from django import forms
from django.conf import settings

from core.mail import send_mail_template


class ContactCourse(forms.Form):
    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem / Dúvida', widget=forms.Textarea, required=False)

    def send_email(self, course):
        subject = '[%s] - Contato' % course
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message']
        }
        template_name = 'courses/contact_email.html'
        send_mail_template(subject, template_name, context, [settings.CONTACT_EMAIL])

accounts/views.py
from django.conf import settings
from django.shortcuts import render, redirect

from .forms import RegisterForm


# Create your views here.
def register(request):
    template_name = 'registration/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(settings.LOGIN_URL)
    else:
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)

core/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    # renderiza o arquivo home.html localizado na pasta template
    return render(request, 'home.html', {'usuario': 'Roberto'})


def contact(request):
    return render(request, 'contact.html')

courses/views.py
from django.shortcuts import render, get_object_or_404

from .forms import ContactCourse
from .models import Course


# Create your views here.
def courses(request):
    template_name = 'courses/index.html'
    courses_list = Course.objects.all()
    context = {
        'courses': courses_list
    }
    return render(request, template_name, context)


def details(request, slug):
    template_name = 'courses/details.html'
    course = get_object_or_404(Course, slug=slug)  # Executa a query e exibe a pagina 404 quando o registro não existir
    # course = Course.objects.get(pk=pk)
    context = {}
    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_email(course)
            form = ContactCourse()
    else:
        form = ContactCourse()
    context['course'] = course
    context['form'] = form
    return render(request, template_name, context)

core/templates/base.html
<!doctype html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância"/>
    <title>Simple MOOC</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    {% block block_css %}{% endblock %}
</head>
<body>
<header class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'core:home' %}">SIMPLE MOOC</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a class="nav-link" href="{% url 'core:home' %}">Início</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'courses:index' %}">Cursos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:contact' %}">Contato</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Sair</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Entrar</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

{% block splash %}{% endblock %}

<main class="container-fluid">
    {% block content %}{% endblock %}
</main>

<footer class="footer">
    Simple MOOC - Uma simples plataforma de ensino a distância
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
{% block block_js %}{% endblock %}
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div class="col">
    <h1>Fale conosco</h1>
    <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para
        contato:</p>
    <h4>Links</h4>
    <ul>
        <li>E-mail: <a href="mailto:contato@simplemooc.org">contato@simplemooc.org</a></li>
        <li>Twitter: <a href="https://twitter.com/simplemooc">@simplemooc</a></li>
    </ul>
</div>
{% endblock %}

core/templates/home.html
{% extends "base.html" %}

{% block splash %}
<!-- Masthead-->
<section class="jumbotron">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8">
            <h1 class="fw-light">Uma Simples Plataforma de Ensino a Distância</h1>
            <h2 class="lead">
                O Simple MOOC visa simplificar o ensino à distância, provendo ferramentas objetivas e de fácil uso para
                cursos a distância.
            </h2>
            <p>
                <a class="btn btn-primary btn-lg" href="#about" role="button">Saiba mais</a>
            </p>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<!-- About Section-->
<section id="about" class="album bg-light pt-5 pb-5 shadow-sm">
    <div class="container">
        <div class="row pt-5">
            <div class="col-lg-4 mb-3 d-flex align-items-stretch">
                <div class="card shadow-sm">
                    <img src="http://placehold.it/400x250" alt="Vídeo aulas e materiais digitais." class="card-img-top">
                    <div class="card-body content">
                        <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
                        <h3>Publique suas aulas</h3>
                        <p class="card-text">
                            O Simple MOOC tem um sistema simples e prático para que o professor disponibilize
                            vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 mb-3 d-flex align-items-stretch">
                <div class="card shadow-sm">
                    <img src="http://placehold.it/400x250" alt="Fórum de Dúvidas" class="card-img-top">
                    <div class="card-body content">
                        <h4 class="content-subhead">Fórum de Dúvidas</h4>
                        <h3>Interaja com seus Alunos</h3>
                        <p class="card-text">
                            No Simple MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam
                            interagir com você e com os outros alunos
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 mb-3 d-flex align-items-stretch">
                <div class="card shadow-sm">
                    <img src="http://placehold.it/400x250" alt="Exercícios" class="card-img-top">
                    <div class="card-body content">
                        <h4 class="content-subhead">Exercícios</h4>
                        <h3>Crie exercícios para avaliar seus alunos</h3>
                        <p class="card-text">
                            Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de
                            notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 mb-3 d-flex align-items-stretch">
                <div class="card shadow-sm">
                    <img src="http://placehold.it/400x250" alt="Mural de Avisos" class="card-img-top">
                    <div class="card-body content">
                        <h4 class="content-subhead">Mural de Avisos</h4>
                        <h3>Envie anúncios diretamente para os alunos</h3>
                        <p class="card-text">
                            Organize os avisos do seu curso de forma fácil e simples.
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
{% endblock %}

courses/templates/courses/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

courses/templates/courses/details.html
{% extends "base.html" %}

{% load static %}

{% block splash %}
<section class="splash">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8">
            <h1 class="splash-head">{{ course }}</h1>
            <h2 class="splash-subhead">
                {{ course.description }}
            </h2>
            <p>
                <a href="#" class="pure-button primary-button">Inscreva-se</a>
            </p>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<article class="blog-post">
    <h2 class="blog-post-title mb-1">Sobre o Curso</h2>
    <hr/>
    <p>{{ course.about|linebreaks }}</p>
    <div>
        {% if course.image %}
        <img src="{{ course.image.url }}" alt=""/>
        {% else %}
        <img src="{% static 'img/course-image.png' %}" alt=""/>
        {% endif %}
        <h4>Dúvidas?</h4>
        <p>
            <a href="#contato" title="" class="pure-button">Fale Conosco</a>
        </p>
    </div>
</article>

<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3>Tire sua dúvida sobre o Curso</h3>
        {% if is_valid %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            Você enviou o formulário com sucesso
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}

        <form action="#contato" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Enviar</button>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

courses/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<h3 class="pb-4 mb-4 fst-italic border-bottom">Listagem de Cursos do SimpleMOOC</h3>
<p>Abaixo a lista de cursos disponíveis na plataforma</p>

<div class="col">
    {% for course in courses %}
    <div class="row content-ribbon">
        <div class="col-auto d-none d-lg-block">
            <a href="{{ course.get_absolute_url }}">
                {% if course.image %}
                <img src="{{ course.image.url }}" alt="{{ course.name }}"/>
                {% else %}
                <img src="{% static 'img/course-image.png' %}" alt="{{ course.name }}"/>
                {% endif %}
            </a>
        </div>
        <div class="col p-4 d-flex flex-column position-static">
            <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a></h4>
            {{ course.description|linebreaks }}
        </div>
    </div>
    {% empty %} <!-- Executa apenas quando a lista estiver vazia -->
    <div class="row content-ribbon">
        <div class="col-auto d-none d-lg-block">
            <p>Nenhum curso está disponível na plataforma</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}